server:
  port: 8080

ddlAuto : ${init.ddlAuto:create}
database: ${init.database:mysql}
dbName: ${init.dbName:shop}
dbPort: ${init.dbPort:3306}

host: ${init.host:http://localhost:}
dbDomain: ${init.dbDomain:localhost}

#essential
# java -jar -Dspring.profiles.active=[dev or prod] [jarFile].jar
# --init.[options]=[value] . . .
dbUser: ${init.dbUser:root}
dbPasswd: ${init.dbPasswd:1234}
jwtSecret : ${init.jwtSecret:1qw2#ER$}


spring:
  datasource:
    url: jdbc:${database}://${dbDomain}:${dbPort}/${dbName}?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: ${dbUser}
    password: ${dbPasswd}

  jpa:
    hibernate:
      ddl-auto: ${ddlAuto}
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 4f66eba022302136ac0b9c64e503c457
            client-secret: 6JMtuxi3wOBJJehwu6MQiw94IpdXT1N7
            redirect-uri: ${kakaoRedirectUri}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: kakao
          google:
            client-id: 801204202081-b4v8dravllca4ng03dtof6ktcnjsiqpd.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: ${googleRedirectUri}
            scope:
              - email
              - profile
            client-name: google
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      enabled: true

jwt:
  isuuer: reactdemo
  secret-key: ${jwtSecret}

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace